# Generated by Django 3.2.5 on 2021-07-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(choices=[('gujarati', 'GUJARATI'), ('Hindi', 'HINDI'), ('English', 'ENGLISH'), ('Science', 'SCIENCE'), ('Mathematics', 'MATHEMATICS'), ('Social Study', 'SOCIAL STUDY')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='usermanage',
            name='userImg',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
