# Generated by Django 3.2.5 on 2021-07-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20210703_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='standard',
            field=models.CharField(choices=[('12', 12), ('11', 11), ('10', 10), ('9', 9), ('8', 8), ('7', 7), ('6', 6), ('5', 5)], default='', max_length=50),
            preserve_default=False,
        ),
    ]
