# Generated by Django 3.2.5 on 2021-07-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_chapter_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='notes',
            field=models.FileField(default='', upload_to='media/notes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='presentation',
            field=models.FileField(default='', upload_to='media/files_presentations'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='video',
            field=models.FileField(default='', upload_to='media/video'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='subject',
            field=models.CharField(choices=[('Gujarati', 'Gujarati'), ('Hindi', 'Hindi'), ('English', 'English'), ('Science', 'Science'), ('Mathematics', 'Mathematics'), ('Social Study', 'Social-Study')], max_length=50),
        ),
    ]
