# Generated by Django 3.2.5 on 2021-07-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20210703_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=5000)),
                ('chapter_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='chapter',
            name='notes',
            field=models.FileField(upload_to='lacture/notes'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='presentation',
            field=models.FileField(upload_to='lacture/files_presentations'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='video',
            field=models.FileField(upload_to='lacture/video'),
        ),
    ]
