# Generated by Django 3.2.5 on 2021-07-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='reply',
            new_name='comment_reply',
        ),
    ]
