# Generated by Django 3.2.5 on 2021-07-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_rename_reply_reply_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='chapter_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
