# Generated by Django 3.2.5 on 2021-07-03 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_reply_chapter_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='study.comment'),
        ),
    ]
