# Generated by Django 3.2.5 on 2021-07-03 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_auto_20210703_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
